#!/usr/bin/env python3
"""Generate an N64Recomp symbol TOML (dump.toml) from splat/spimdisasm .s output.

We use N64Recomp's symbol-TOML input mode (symbols_file_path) instead of ELF mode,
because this machine has no MIPS assembler to build an ELF. spimdisasm conveniently
emits a `nonmatching <name>, <size>` line before every function's `glabel`, and the
first instruction comment gives `/* ROM VRAM HEX */`, so we can recover name/vram/size
for every function directly from the disassembly.

Usage: python gen_symbols.py [--overlays]
  (default: fixed segment only — entry + main; --overlays also adds ovl_a/ovl_b)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASM = ROOT / "disasm" / "asm"
OUT = ROOT / "syms" / "dump.toml"

# (section name, rom_start, vram_start, text_size, asm_file)
FIXED = [
    ("entry", 0x1000, 0x80000400, 0x50, "1000.s"),
    ("main", 0x1050, 0x80000450, 0x2A9B0 - 0x1050, "1050.s"),
]
OVERLAYS = [
    ("ovl_a", 0xA21750, 0x80090000, 0x33BC0, "A21750.s"),
    ("ovl_b", 0xA69570, 0x80090000, 0x55F70, "A69570.s"),
]

NONMATCH = re.compile(r"^nonmatching\s+(\S+),\s*(0x[0-9A-Fa-f]+)")
GLABEL = re.compile(r"^glabel\s+(\S+)")
COMMENT = re.compile(r"/\*\s*[0-9A-Fa-f]+\s+([0-9A-Fa-f]{8})\s")


def parse_functions(path: Path):
    """Return list of (name, vram, size) in file order."""
    funcs = []
    pending_size = None
    cur_name = None
    cur_size = None
    awaiting_vram = False
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = NONMATCH.match(line)
        if m:
            pending_size = int(m.group(2), 16)
            continue
        g = GLABEL.match(line)
        if g:
            cur_name = g.group(1)
            cur_size = pending_size
            pending_size = None
            awaiting_vram = True
            continue
        if awaiting_vram:
            c = COMMENT.search(line)
            if c:
                funcs.append([cur_name, int(c.group(1), 16), cur_size])
                awaiting_vram = False
    # Fill any missing sizes from the next function's vram delta.
    for i, fn in enumerate(funcs):
        if fn[2] is None:
            if i + 1 < len(funcs):
                fn[2] = funcs[i + 1][1] - fn[1]
            else:
                fn[2] = 4
    return funcs


def main():
    sections = FIXED + (OVERLAYS if "--overlays" in sys.argv else [])
    seen = {}
    lines = ["# Autogenerated from splat disassembly by tools/gen_symbols.py", ""]
    total = 0
    for name, rom, vram, size, fname in sections:
        funcs = parse_functions(ASM / fname)
        lines += [f"[[section]]", f'name = "{name}"',
                  f"rom = 0x{rom:08X}", f"vram = 0x{vram:08X}",
                  f"size = 0x{size:X}", "", "functions = ["]
        for fn_name, fn_vram, fn_size in funcs:
            # Disambiguate names that collide across overlay sections.
            out_name = fn_name
            if out_name in seen and seen[out_name] != (name, fn_vram):
                out_name = f"{fn_name}_{name}"
            seen[out_name] = (name, fn_vram)
            lines.append(
                f'    {{ name = "{out_name}", vram = 0x{fn_vram:08X}, size = 0x{fn_size:X} }},'
            )
        lines += ["]", ""]
        total += len(funcs)
        print(f"  {name:6} {len(funcs):4} functions  (rom 0x{rom:06X}, vram 0x{vram:08X})")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {total} functions across {len(sections)} sections -> {OUT}")


if __name__ == "__main__":
    main()
